/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VelemenyekRouteImport } from './routes/velemenyek'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as ArlistaRouteImport } from './routes/arlista'
import { Route as IndexRouteImport } from './routes/index'

const VelemenyekRoute = VelemenyekRouteImport.update({
  id: '/velemenyek',
  path: '/velemenyek',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const ArlistaRoute = ArlistaRouteImport.update({
  id: '/arlista',
  path: '/arlista',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arlista': typeof ArlistaRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/velemenyek': typeof VelemenyekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arlista': typeof ArlistaRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/velemenyek': typeof VelemenyekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arlista': typeof ArlistaRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/velemenyek': typeof VelemenyekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arlista' | '/szolgaltatasok' | '/velemenyek'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arlista' | '/szolgaltatasok' | '/velemenyek'
  id: '__root__' | '/' | '/arlista' | '/szolgaltatasok' | '/velemenyek'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArlistaRoute: typeof ArlistaRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
  VelemenyekRoute: typeof VelemenyekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/velemenyek': {
      id: '/velemenyek'
      path: '/velemenyek'
      fullPath: '/velemenyek'
      preLoaderRoute: typeof VelemenyekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arlista': {
      id: '/arlista'
      path: '/arlista'
      fullPath: '/arlista'
      preLoaderRoute: typeof ArlistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArlistaRoute: ArlistaRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
  VelemenyekRoute: VelemenyekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
